<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="local" nsURI="http://org.palladiosimulator.edp2/LocalRepository/1.0"
    nsPrefix="local">
  <eClassifiers xsi:type="ecore:EClass" name="LocalDirectoryRepository" eSuperTypes="../../org.palladiosimulator.edp2/model/EDP2.ecore#//Repository/Repository">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Repository which provides access to data stored in a local directory."/>
    </eAnnotations>
    <eOperations name="convertUriStringToFile" ordered="false" lowerBound="1" eType="#//File">
      <eParameters name="uriString" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" instanceClassName="java.io.File"
      abstract="true" interface="true"/>
</ecore:EPackage>
