/**
 */
package org.palladiosimulator.edp2.local.provider;

import org.eclipse.emf.edit.provider.IItemStyledLabelProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class LocalItemProviderAdapterFactory extends LocalItemProviderAdapterFactoryGen {
	
	public LocalItemProviderAdapterFactory()
	{
		supportedTypes.add(IItemStyledLabelProvider.class);
	}

}
